/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttributeDetail: typeof import('./src/components/detail/grammar/AttributeDetail.vue')['default']
    CFArrayDetail: typeof import('./src/components/detail/cf-object/CFArrayDetail.vue')['default']
    CFDataPointerDetail: typeof import('./src/components/detail/cf-pointer/CFDataPointerDetail.vue')['default']
    CFIntegerArrayPropertyDetail: typeof import('./src/components/detail/cf-property/CFIntegerArrayPropertyDetail.vue')['default']
    CFIntegerPointerDetail: typeof import('./src/components/detail/cf-pointer/CFIntegerPointerDetail.vue')['default']
    CFIntegerPropertyDetail: typeof import('./src/components/detail/cf-property/CFIntegerPropertyDetail.vue')['default']
    CFIntegerPropertyView: typeof import('./src/components/detail/CFIntegerPropertyView.vue')['default']
    CFObjectView: typeof import('./src/components/detail/CFObjectView.vue')['default']
    CFPointerDetail: typeof import('./src/components/detail/cf-pointer/CFPointerDetail.vue')['default']
    CFPointerPropertyDetail: typeof import('./src/components/detail/cf-property/CFPointerPropertyDetail.vue')['default']
    CFPropertyView: typeof import('./src/components/detail/CFPropertyView.vue')['default']
    CFStringDetail: typeof import('./src/components/detail/cf-object/CFStringDetail.vue')['default']
    CFTreeView: typeof import('./src/components/CFTreeView.vue')['default']
    ClassDetail: typeof import('./src/components/detail/grammar/ClassDetail.vue')['default']
    ClassView: typeof import('./src/components/detail/grammar/ClassView.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NoFile: typeof import('./src/components/detail/NoFile.vue')['default']
    NoSelection: typeof import('./src/components/detail/NoSelection.vue')['default']
    NoView: typeof import('./src/components/detail/NoView.vue')['default']
  }
}
